sports_betting_homepage:
    path:     /sports
    defaults: { _controller: SportsBettingBundle:Bet:index }

sports_betting_sports_bets:
    path:     /sports/{sportId}/bets
    defaults: { _controller: SportsBettingBundle:Bet:getSportBets }
