services:
#    sports_betting.example:
#        class: Andersen\SportsBettingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

services:
    app.command.my_command:
        class: Andersen\SportsBettingBundle\Command\CreateGamesCommand
        arguments: ["@doctrine.orm.entity_manager"]
