services:
#    sports_betting.example:
#        class: Andersen\SportsBettingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    sports_betting.command.create_games:
        class: Andersen\SportsBettingBundle\Command\CreateGamesCommand
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: console.command }

    sports_betting.command.create_coefficient:
            class: Andersen\SportsBettingBundle\Command\CreateCoefficientCommand
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
                - { name: console.command }

    api_key_user_provider:
        class: Andersen\SportsBettingBundle\Security\ApiKeyUserProvider
        arguments: ["@doctrine.orm.entity_manager"]

    apikey_authenticator:
            class:  Andersen\SportsBettingBundle\Security\ApiKeyAuthenticator
            public: false
