sports_betting_api:
    resource: "@SportsBettingBundle/Resources/config/routing.yml"
    prefix:   /api

sports_betting_frontend:
    defaults: { _controller: SportsBettingBundle:Bet:frontend }
    path: /{url}
    requirements:
        url: ".*"
