<?php

namespace Andersen\SportsBettingBundle\Repository;

/**
 * BetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BetRepository extends \Doctrine\ORM\EntityRepository
{
public function findAllBets($sportId)
{
    $allBets = $this->getEntityManager()->getRepository("SportsBettingBundle:Bet");
    $query = $allBets->createQueryBuilder('bet')
        ->where('bet.sport > :sport')
        ->setParameter('sport', $sportId)
        ->getQuery();
    return $query->getResult();

}
}
