<?php

namespace Andersen\SportsBettingBundle\Repository;

/**
 * CoefficientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoefficientRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTeamOfTypeCoefficient($gameId, $betValue)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('t', 'c', 'g')
            ->from('SportsBettingBundle:Coefficient', 'c')
            ->leftJoin('c.team', 't')
            ->leftJoin('c.game', 'g')
            ->where("c.game = :gameId")
            ->andWhere("c.typeCoefficient = :betValue")
            ->setParameter('gameId', $gameId)
            ->setParameter('betValue', $betValue);
        $getQuery = $query->getQuery()->getSingleResult();
        return $getQuery;
    }
}
