<?php

namespace Andersen\SportsBettingBundle\Repository;

/**
 * CoefficientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoefficientRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTeamOfTypeCoefficient($coefficientId)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('t', 'c', 'g')
            ->from('SportsBettingBundle:Coefficient', 'c')
            ->leftJoin('c.team', 't')
            ->leftJoin('c.game', 'g')
            ->where("c.id = :coefficientId")
            ->setParameter('coefficientId', $coefficientId);
        $getQuery = $query->getQuery()->getSingleResult();
        return $getQuery;
    }

    public function selectTeamCoefficientByGameId($gameId, $teamId)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('c')
            ->from('SportsBettingBundle:Coefficient', 'c')
            ->where("c.game = :gameId");
        if ($teamId === null) {
            $query = $query->andWhere("c.team IS NULL");
        } else {
            $query = $query->andWhere("c.team = :teamId")
                ->setParameter('teamId', $teamId);
        }

        $query = $query->setParameter('gameId', $gameId);
        $getQuery = $query->getQuery()->getSingleResult();

        return $getQuery;
    }
}
