<?php

namespace Andersen\SportsBettingBundle\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllGamesOfSportType($sportId)
    {
        $gamesFromSportId = $this
            ->getEntityManager()
            ->createQueryBuilder()
            ->select('g', 's')
            ->from('SportsBettingBundle:Game', 'g')
            ->leftJoin('g.sport', 's')
            ->where("s.id = :sportId")
            ->setParameter('sportId', $sportId);
        $query = $gamesFromSportId->getQuery()->getResult();
        return $query;
    }
}
