<?php

namespace Andersen\SportsBettingBundle\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $sportId
     * @return array
     *
     * /sports/{sportId}/games
     *
     * get games of sport type
     */
    public function findAllGamesOfSportType($sportId)
    {
        $gamesFromSportId = $this
            ->getEntityManager()
            ->createQueryBuilder()
            ->select('g', 's')
            ->from('SportsBettingBundle:Game', 'g')
            ->leftJoin('g.sport', 's')
            ->where("s.id = :sportId")
            ->setParameter('sportId', $sportId);
        $query = $gamesFromSportId->getQuery()->getResult();
        return $query;
    }

    public function FindGamesWithoutCoefficients()
    {
        $query = $this
            ->getEntityManager()
            ->createQueryBuilder()
            ->select('g', 'c')
            ->from('SportsBettingBundle:Game', 'g')
            ->leftJoin('g.coefficients', 'c')
            ->where("g.teamWinner is NULL")
            ->andWhere("c.id is NULL");
//            ->setParameter('NULL', NULL);
        $query = $query->getQuery()->getResult();
        return $query;
    }
}
