<?php

namespace Andersen\SportsBettingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportRepository extends EntityRepository
{
    public function findAllSports()
    {
        return $this->getEntityManager()->getRepository("SportsBettingBundle:Sport")->findAll();
    }
}
