<?php

namespace Andersen\SportsBettingBundle\Repository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function findGamesOfSportType($sportId)
    {
        $query = $this
            ->getEntityManager()
            ->createQueryBuilder()
            ->select('t', 's')
            ->from('SportsBettingBundle:Team', 't')
            ->leftJoin('t.sport', 's')
            ->where("s.id = :sportId")
            ->setParameter('sportId', $sportId);
        $query = $query->getQuery()->getResult();
        return $query;
    }

    public function findSportGameTeams($sportId, $gameId)
    {
        $query = $this
            ->getEntityManager()
            ->createQueryBuilder()
            ->select('t', 'g', 's')
            ->from('SportsBettingBundle:Team', 't')
            ->leftJoin('t.games', 'g')
            ->leftJoin('t.sport', 's')
            ->where('t.games = :gameId')
            ->andWhere('t.sport = :sportId')
            ->setParameter('gameId', $gameId)
            ->setParameter('$sportId', $sportId);
        $query = $query->getQuery()->getResult();
        return$query;
    }
}
