<?php

namespace Andersen\SportsBettingBundle\Repository;

/**
 * TeamResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamResultRepository extends \Doctrine\ORM\EntityRepository
{
}
