<?php

namespace Andersen\SportsBettingBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserById($userId)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('u')
            ->from('SportsBettingBundle:User', 'u')
            ->where("u.id = :userId")
            ->setParameter('userId', $userId);
        $query = $query->getQuery()->getResult();

        return $query;
    }
}
